//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineDiary.BotLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicineDiary.BotLogic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите требуемый язык из поддерживаемых / Select the desired language from the supported ones.
        /// </summary>
        internal static string Change_Language {
            get {
                return ResourceManager.GetString("Change_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препарат : {0}, 
        ///Частота приёма:  {1} р. в д., 
        ///Кол-во дней: {2} (всего {3} приёмов),
        ///Время приёма: {3}.
        /// </summary>
        internal static string ConfirmMedicine {
            get {
                return ResourceManager.GetString("ConfirmMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для определения часового пояса требуется ввести твоё текущее время в 24-часовом формате ЧЧ:MM.
        /// </summary>
        internal static string GetTimeMessage {
            get {
                return ResourceManager.GetString("GetTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык чата изменён.
        /// </summary>
        internal static string LanguageSet_Success {
            get {
                return ResourceManager.GetString("LanguageSet_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported language is selected, select from the list of available languages: {0}.
        /// </summary>
        internal static string LanguageSet_WrongLanguage {
            get {
                return ResourceManager.GetString("LanguageSet_WrongLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время установлено, вы можете пользоваться приложением.
        /// </summary>
        internal static string TimeSet_Success {
            get {
                return ResourceManager.GetString("TimeSet_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при установке времени, введите еще раз ваше текушее время в 24-часовом формате ЧЧ:ММ (напимер 14:46).
        /// </summary>
        internal static string TimeSet_WrongTimeFormat {
            get {
                return ResourceManager.GetString("TimeSet_WrongTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка диапазона времени. Время должно быть в диапазоне 00:00 - 23:59..
        /// </summary>
        internal static string TimeSet_WrongTimeRange {
            get {
                return ResourceManager.GetString("TimeSet_WrongTimeRange", resourceCulture);
            }
        }
    }
}
